version: '3.8'

networks:
  news_network:
    external: false

services:

  postgresdb:
    container_name: news_pg
    image: postgres:14-alpine
    restart: always
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    - pgVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: news
      POSTGRES_USER: root
      POSTGRES_DB: db_news

    ports:
    - 5432:5432
    networks:
      - news_network

volumes:
  pgVolume:
